### ISSUE TITLE
Video URL update is required

### ISSUE THREAD

**Issue by yukanechika** [renesas-rz/meta-rzg-demos#1]
Hello,

Following line's URL seems to be old.
https://github.com/renesas-rz/meta-rzg-demos/blob/b121be1c4f01ce26dba0af32300156c2de62a569/meta-rzg1/qt-hmi-demo/recipes-qt/examples/qt5-launch-demo_1.0.bb#L12

In my enviroment, this modification fix the build error.
```diff
-           http://www.renesas.com/ja-jp/media/products/microcontrollers-microprocessors/rz/rzg/qt-videos/renesas-bigideasforeveryspace.mp4;name=video \
+           http://www.renesas.com/jp/ja/img/products/media/auto-j/microcontrollers-microprocessors/rz/rzg/qt-videos/renesas-bigideasforeveryspace.mp4;name=video \
```

**Comment by renesas-rz** [comment]
Thank you for reporting!
The URL has been fixed.
